[project]
name = "mcp-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-genai>=1.7.0",
    "mcp[cli]>=1.5.0",
    "python-dotenv>=1.0.1",
]
